const AIML_ENDPOINT = "https://api.aimlapi.com/v1/images/generations";
const AIML_MODEL = "blackforestlabs/flux-2-klein-9b";
const BFL_ENDPOINT = "https://api.eu.bfl.ai/v1/flux-2-klein-9b";
const AIML_MODEL_LABEL = "AI/ML API · FLUX.2 Klein 9B";
const BFL_MODEL_LABEL = "Black Forest Labs · FLUX.2 Klein 9B";

type AimlImageResponse = {
  data?: Array<{ url?: string | null; b64_json?: string | null }>;
  meta?: { usage?: { credits_used?: number; usd_spent?: number } };
  error?: { message?: string } | string;
  detail?: unknown;
};

type BflSubmitResponse = {
  id?: string;
  polling_url?: string;
  detail?: unknown;
};

type BflResultResponse = {
  status?: string;
  cost?: number;
  result?: { sample?: string } | null;
};

export type GeneratedImage = {
  bytes: ArrayBuffer;
  contentType: string;
  provider: string;
  costCredits: number | null;
};

function assertBflUrl(value: string, delivery: boolean): URL {
  const url = new URL(value);
  const validPollingHost = url.hostname === "api.bfl.ai" || url.hostname === "api.eu.bfl.ai" || url.hostname === "api.us.bfl.ai";
  const validDeliveryHost = url.hostname.startsWith("delivery.") && url.hostname.endsWith(".bfl.ai");
  if (url.protocol !== "https:" || (delivery ? !validDeliveryHost : !validPollingHost)) {
    throw new Error("Black Forest Labs a retourné une adresse inattendue.");
  }
  return url;
}

function assertAimlImageUrl(value: string): URL {
  const url = new URL(value);
  const hostname = url.hostname.toLowerCase().replace(/^\[|\]$/g, "");
  const ipv4 = hostname.match(/^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/)?.slice(1).map(Number);
  const isPrivateIpv4 = Boolean(ipv4 && (
    ipv4.some((part) => part > 255)
    || ipv4[0] === 0
    || ipv4[0] === 10
    || ipv4[0] === 127
    || (ipv4[0] === 100 && ipv4[1] >= 64 && ipv4[1] <= 127)
    || (ipv4[0] === 169 && ipv4[1] === 254)
    || (ipv4[0] === 172 && ipv4[1] >= 16 && ipv4[1] <= 31)
    || (ipv4[0] === 192 && ipv4[1] === 168)
    || (ipv4[0] === 198 && (ipv4[1] === 18 || ipv4[1] === 19))
    || ipv4[0] >= 224
  ));
  const isPrivateIpv6 = hostname === "::" || hostname === "::1"
    || hostname.startsWith("fc") || hostname.startsWith("fd") || hostname.startsWith("fe8")
    || hostname.startsWith("fe9") || hostname.startsWith("fea") || hostname.startsWith("feb");
  const isLocalName = hostname === "localhost" || hostname.endsWith(".localhost")
    || hostname.endsWith(".local") || hostname.endsWith(".internal");
  if (
    url.protocol !== "https:"
    || Boolean(url.username || url.password)
    || Boolean(url.port && url.port !== "443")
    || isPrivateIpv4
    || isPrivateIpv6
    || isLocalName
  ) {
    throw new Error("AI/ML API a retourné une adresse inattendue.");
  }
  return url;
}

async function fetchAimlImage(value: string): Promise<Response> {
  let url = assertAimlImageUrl(value);
  for (let redirect = 0; redirect <= 3; redirect += 1) {
    const response = await fetch(url, {
      redirect: "manual",
      signal: AbortSignal.timeout(30_000),
    });
    if (![301, 302, 303, 307, 308].includes(response.status)) return response;

    const location = response.headers.get("location");
    if (!location) throw new Error("AI/ML API a retourné une redirection incomplète.");
    url = assertAimlImageUrl(new URL(location, url).toString());
  }
  throw new Error("AI/ML API a retourné trop de redirections.");
}

function decodeBase64Image(value: string): ArrayBuffer {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes.buffer;
}

async function readImageResponse(response: Response): Promise<{ bytes: ArrayBuffer; contentType: string }> {
  if (!response.ok) throw new Error("L’avatar généré n’a pas pu être récupéré.");
  const contentType = response.headers.get("content-type")?.split(";")[0] ?? "image/png";
  if (!contentType.startsWith("image/")) throw new Error("FLUX a retourné un fichier inattendu.");
  const bytes = await response.arrayBuffer();
  if (bytes.byteLength === 0 || bytes.byteLength > 12_000_000) {
    throw new Error("La taille de l’avatar généré est invalide.");
  }
  return { bytes, contentType };
}

async function generateViaAiml(prompt: string, apiKey: string): Promise<GeneratedImage> {
  const response = await fetch(AIML_ENDPOINT, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: AIML_MODEL,
      prompt,
      n: 1,
      size: "1024x1024",
      // Keep the generated bytes in the trusted API response. AI/ML may return
      // short-lived URLs on different CDN hosts, which makes a safe hostname
      // allowlist brittle and can discard an image after it has been billed.
      response_format: "b64_json",
    }),
    signal: AbortSignal.timeout(90_000),
  });
  const result = await response.json() as AimlImageResponse;
  if (!response.ok) {
    console.error("AI/ML image error", response.status, result.error ?? result.detail);
    throw new Error("FLUX n’a pas accepté la génération de cet avatar.");
  }

  const first = result.data?.[0];
  let bytes: ArrayBuffer;
  let contentType = "image/png";
  if (first?.url) {
    const image = await fetchAimlImage(first.url);
    const downloaded = await readImageResponse(image);
    bytes = downloaded.bytes;
    contentType = downloaded.contentType;
  } else if (first?.b64_json) {
    bytes = decodeBase64Image(first.b64_json);
  } else {
    throw new Error("FLUX n’a retourné aucune image exploitable.");
  }

  if (bytes.byteLength === 0 || bytes.byteLength > 12_000_000) {
    throw new Error("La taille de l’avatar généré est invalide.");
  }
  return {
    bytes,
    contentType,
    provider: AIML_MODEL_LABEL,
    costCredits: typeof result.meta?.usage?.credits_used === "number"
      ? result.meta.usage.credits_used
      : null,
  };
}

export function buildHistoricalAvatarPrompt(
  name: string,
  subtitle: string,
  description: string,
  visualDescription: string,
): string {
  const details = visualDescription.trim().slice(0, 800);
  return [
    `Square illustrated historical portrait avatar of ${name}, ${subtitle}.`,
    `Character context: ${description.slice(0, 900)}.`,
    details ? `Distinctive visual attributes: ${details}.` : "Use historically and mythologically recognizable attributes.",
    "Head and upper chest only, face large and centered, direct or three-quarter gaze, one iconic attribute clearly visible near the face.",
    "Refined hand-drawn engraving and painted parchment style, natural muted pigments, warm ivory, charcoal, ochre and restrained deep colors.",
    "Dignified and believable, subtle texture, no photorealistic plastic skin, no neon colors, no modern clothing.",
    "Simple atmospheric background, readable inside a circular map marker. No frame, no border, no text, no letters, no watermark.",
  ].join(" ");
}

async function generateViaBfl(prompt: string, apiKey: string): Promise<GeneratedImage> {
  const submit = await fetch(BFL_ENDPOINT, {
    method: "POST",
    headers: {
      accept: "application/json",
      "Content-Type": "application/json",
      "x-key": apiKey,
    },
    body: JSON.stringify({ prompt, width: 1024, height: 1024 }),
    signal: AbortSignal.timeout(20_000),
  });
  const submitted = await submit.json() as BflSubmitResponse;
  if (!submit.ok || !submitted.polling_url) {
    console.error("BFL submit error", submit.status, submitted.detail);
    throw new Error("FLUX n’a pas accepté la génération de cet avatar.");
  }

  const pollingUrl = assertBflUrl(submitted.polling_url, false);
  let ready: BflResultResponse | null = null;
  for (let attempt = 0; attempt < 45; attempt += 1) {
    await new Promise((resolve) => setTimeout(resolve, 700));
    const response = await fetch(pollingUrl, {
      headers: { accept: "application/json", "x-key": apiKey },
      signal: AbortSignal.timeout(12_000),
    });
    const result = await response.json() as BflResultResponse;
    if (!response.ok) throw new Error("La génération FLUX ne répond plus.");
    if (result.status === "Ready") {
      ready = result;
      break;
    }
    if (result.status === "Error" || result.status === "Failed" || result.status === "Content Moderated" || result.status === "Request Moderated") {
      throw new Error("FLUX n’a pas pu produire cet avatar.");
    }
  }

  const sample = ready?.result?.sample;
  if (!sample) throw new Error("FLUX met trop longtemps à produire cet avatar.");

  const deliveryUrl = assertBflUrl(sample, true);
  const image = await fetch(deliveryUrl, { signal: AbortSignal.timeout(20_000) });
  if (!image.ok) throw new Error("L’avatar généré n’a pas pu être récupéré.");
  const contentType = image.headers.get("content-type")?.split(";")[0] ?? "image/jpeg";
  if (!contentType.startsWith("image/")) throw new Error("FLUX a retourné un fichier inattendu.");
  const bytes = await image.arrayBuffer();
  if (bytes.byteLength === 0 || bytes.byteLength > 12_000_000) {
    throw new Error("La taille de l’avatar généré est invalide.");
  }

  return {
    bytes,
    contentType,
    provider: BFL_MODEL_LABEL,
    costCredits: typeof ready?.cost === "number" ? ready.cost : null,
  };
}

export async function generateFluxAvatar(prompt: string): Promise<GeneratedImage> {
  const aimlApiKey = process.env.AIML_API_KEY;
  if (aimlApiKey) return generateViaAiml(prompt, aimlApiKey);

  const bflApiKey = process.env.BFL_API_KEY;
  if (bflApiKey) return generateViaBfl(prompt, bflApiKey);

  throw new Error("La clé AI/ML API n’est pas encore configurée sur le serveur.");
}
